/**
 * Solution types and constants for the PACOUPA application
 */

import { Solution } from "@/types";
import BiomasseIcon from "@/assets/solutions/Biomasse.png";
import GeothermieIcon from "@/assets/solutions/géothermie.png";
import PACIcon from "@/assets/solutions/PAC.png";
import RCUIcon from "@/assets/solutions/RCU.png";
import SolaireThermiqueIcon from "@/assets/solutions/Solaire thermique.png";

import IllustrationRCU from "@/assets/solutions/primary-illustration/0 — RCU.svg";
import IllustrationGeothermieNappe from "@/assets/solutions/primary-illustration/13 — geothermie nappe.svg";
import IllustrationGeothermieNappeHeatOnly from "@/assets/solutions/primary-illustration/23 — geothermie nappe (heat only).svg";
import IllustrationGeothermieSonde from "@/assets/solutions/primary-illustration/13 — géothermie sonde.svg";
import IllustrationGeothermieSondeHeatOnly from "@/assets/solutions/primary-illustration/23 — géothermie sonde (heat only).svg";
import IllustrationBiomasse from "@/assets/solutions/primary-illustration/NA — biomasse.svg";
import IllustrationPacAirEau from "@/assets/solutions/primary-illustration/10 — PAC air eau.svg";
import IllustrationPacAirEauHeatOnly from "@/assets/solutions/primary-illustration/20 — PAC air eau (heat only).svg";
import IllustrationHybride from "@/assets/solutions/primary-illustration/15 — Hybridation PAC chaudière.svg";
import IllustrationHybrideHeatOnly from "@/assets/solutions/primary-illustration/25 — Hybridation PAC chaudière (heat only).svg";
import IllustrationSolaireThermiqueWaterOnly from "@/assets/solutions/primary-illustration/NA — solaire thermique (water only).svg";
import IllustrationCapteurAtmospheriqueWaterOnly from "@/assets/solutions/primary-illustration/4 — capteur atmosphérique (water only).svg";
import IllustrationPacEauxGrisesWaterOnly from "@/assets/solutions/primary-illustration/3 — PAC eaux grises eau (water only).svg";
import IllustrationPacAirEauWaterOnly from "@/assets/solutions/primary-illustration/1 — PAC air eau (water only).svg";
import IllustrationPacAirEauAvecUE from "@/assets/solutions/primary-illustration/50 — PAC Air Eau avec UE.svg";
import IllustrationPacAirEauSansUE from "@/assets/solutions/primary-illustration/51 — PAC Air Eau sans UE.svg";
import IllustrationPacAirExtraitEau from "@/assets/solutions/primary-illustration/53 — PAC Air extrait Eau.svg";
import IllustrationPacAirAirHeatOnly from "@/assets/solutions/primary-illustration/40 — PAC Air Air (heat only).svg";
import IllustrationCetAvecUEWaterOnly from "@/assets/solutions/primary-illustration/31 — CET Air Eau avec UE (water only).svg";
import IllustrationCetSansUEWaterOnly from "@/assets/solutions/primary-illustration/32 — CET Air Eau sans UE (water only).svg";
import IllustrationCetAirExtraitWaterOnly from "@/assets/solutions/primary-illustration/30 — CET Air extrait Eau (water only).svg";

import FicheReseauDeChaleur from "@/assets/solutions/fiche-enr/Réseau de chaleur.pdf";
import FichePacEauGeothermieNappe from "@/assets/solutions/fiche-enr/PAC Eau : Eau géothermie sur nappe.pdf";
import FichePacEauGeothermieSondes from "@/assets/solutions/fiche-enr/PAC Eau : Eau géothermie sur sondes.pdf";
import FicheBiomasse from "@/assets/solutions/fiche-enr/Biomasse.pdf";
import FichePacAirEauCollective from "@/assets/solutions/fiche-enr/PAC Air : Eau Collective.pdf";
import FicheHybridationPacChaudiere from "@/assets/solutions/fiche-enr/Hybridation PAC chaudière.pdf";
import FicheSolaireThermique from "@/assets/solutions/fiche-enr/Solaire thermique.pdf";
import FichePacCapteursAtmospheriques from "@/assets/solutions/fiche-enr/Pac Eau : Eau sur capteurs atmosphériques.pdf";
import FichePacEauxGrises from "@/assets/solutions/fiche-enr/Pac sur Eaux grises : Eau.pdf";
import FichePacAirEauCollectiveEcs from "@/assets/solutions/fiche-enr/PAC Air : Eau collective dédiée à l'Eau chaude sanitaire.pdf";
import FichePacAirEauAvecUe from "@/assets/solutions/fiche-enr/PAC Air : Eau avec unité extérieur.pdf";
import FichePacAirEauSansUe from "@/assets/solutions/fiche-enr/PAC Air : Eau sans unité extérieur.pdf";
import FichePacAirExtraitEau from "@/assets/solutions/fiche-enr/PAC Air extrait : Eau.pdf";
import FichePacAirAir from "@/assets/solutions/fiche-enr/PAC Air : Air.pdf";
import FicheChauffeEauThermodynamiqueAvecUe from "@/assets/solutions/fiche-enr/Chauffe-Eau Thermodynamique (CET) avec unité extérieure.pdf";
import FicheChauffeEauThermodynamiqueSansUe from "@/assets/solutions/fiche-enr/Chauffe-Eau Thermodynamique (CET) sans unité extérieure.pdf";
import FicheChauffeEauThermodynamiqueAirExtrait from "@/assets/solutions/fiche-enr/Chauffe-Eau Thermodynamique (CET) sur Air extrait.pdf";

export const SOLUTIONS: Solution[] = [
  {
    slug: "reseau-chaleur",
    title: "Réseau de chaleur",
    type: "collectif",
    description: "Réseau de canalisations souterraines qui achemine la chaleur jusqu'à l'immeuble.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "Variable selon la distance au réseau existant et les travaux nécessaires",
    costMaintenance: "Inclus dans le contrat de fourniture de chaleur",
    costMwh: "80 € HT/MWh (entre 25 et 180 € HT/MWh)",
    dpeGain: "Pas de gain sur la lettre DPE",
    co2Emissions: "125 g/kWh sur le cycle de vie en moyenne, variable selon les réseaux",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Création d'une tranchée dans la rue pour raccorder le réseau de chaleur à un échangeur placé en chaufferie",
    emitterTypeRequired: "Avoir un plancher chauffant à eau ou radiateur à eau",
    distanceRequirement: "Le réseau de chaleur doit être à moins de 100m du bâtiment",
    indoorSpaceRequired: "Pas de problème de taille de local technique : l'installation en chaufferie ne nécessite qu'un échangeur",
    outdoorSpaceRequired: "",
    otherConditions: [
      "Demande de raccordement : La demande de raccordement se fait en direct sur le site du réseau de chaleur ou sur le site de FCU",
      "Qualité du réseau de distribution : à vérifier avant de changer le système",
      "Niveau d'isolation du bâtiment : Le réseau de chaleur peut délivrer de la haute température pour chauffer des bâtiments quel que soit leur niveau d'isolation",
    ],
    fullDescription:
      "Le réseau de chaleur est un système de canalisations qui permettent d'acheminer vers un ensemble de bâtiments de la chaleur produite localement, à partir d'énergies renouvelables et de récupération. La part d'énergies renouvelables varie d'un réseau à l'autre. C'est la solution à privilégier pour un chauffage collectif, lorsqu'il est disponible.",
    illustration: IllustrationRCU,
    icon: RCUIcon,
    ficheEnr: FicheReseauDeChaleur,
  },
  {
    slug: "pac-eau-eau-nappe-chauffage-ecs",
    title: "Pompe à chaleur Eau / Eau géothermique nappe (chauffage + ECS)",
    type: "collectif",
    description: "Chauffe de l'eau en prélevant de la chaleur dans une nappe via des sondes.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 8 000 à 11 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 90 et 110 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Très faibles émissions de CO₂ : 15 g CO₂/kWhth en phase d'exploitation",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux importants dans les parties extérieures collectives pour le forage dans la nappe phréatique",
    emitterTypeRequired: "Efficace pour bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "La copropriété doit se trouver en zone GMI (orange ou vert). Zone rouge possible mais avec une procédure lourde et incertaine",
    indoorSpaceRequired: "10 à 20 m² nécessaires (machines, équipements hydrauliques, tableaux électriques…)",
    outdoorSpaceRequired: "Deux forages nécessaires à une distance déterminée par les études. La parcelle doit être accessible pour les machines de forage",
    otherConditions: [
      "Le potentiel de la nappe identifiée doit être fort ou très fort",
      "Entretien annuel minimum nécessaire pour garantir le bon fonctionnement",
      "La qualité du réseau de distribution de chaleur est essentielle pour le rendement global",
      "Retour sur investissement : 8 à 15 ans en moyenne",
    ],
    fullDescription:
      "La pompe à chaleur eau-eau géothermique sur nappe utilise la chaleur d'une nappe phréatique pour chauffer l'eau (chauffage et ECS). Très efficace et écologique, idéale si l'espace extérieur permet un forage et donc pas d'unité extérieure. Possible uniquement en rénovation globale ou sur bâtiment récent. Nécessite un régime basse température, compatible avec plancher chauffant.",
    illustration: IllustrationGeothermieNappe,
    icon: GeothermieIcon,
    ficheEnr: FichePacEauGeothermieNappe,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Rouget de l’Isle",
      lieu: "Pantin",
      codeDepartement: "93",
      nbLogements: 151,
      nbm2: 10055,
      anneeConstruction: 1966,
      avantChauffage: "Chaudière gaz et plancher chauffant",
      avantECS: "Chaudière gaz et plancher chauffant",
      apresChauffage: "PAC géothermique et chaudière gaz en appoint",
      apresECS: "PAC géothermique et chaudière gaz en appoint",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["RTWB 208, Trane", "2 chaudières gaz en appoint"],
      maitreOuvrage: "Immobilière 3F",
      bureauEtude: "Anteagroup, Sermet",
      installateur: "Cofely GDF Suez et Sanfor",
      anneeLivraison: 2011,
      avantages: [
        "Baisse des factures énergétiques de 59%",
        "Temps de retour sur investissement (avec subventions) : 6 ans",
        "PAC sur eau de nappe, puits de 68 m de profondeur et espacés de 280 m",
      ],
      images: ["/fiches-reference/13_01_01.jpg", "/fiches-reference/13_01_02.jpg"],
    },
  },
  {
    slug: "pac-eau-eau-nappe-chauffage",
    title: "Pompe à chaleur Eau / Eau géothermique nappe (chauffage seul)",
    type: "collectif",
    description: "Chauffe de l'eau en prélevant de la chaleur dans une nappe via des sondes.",
    hasHeating: true,
    hasEcs: false,
    hasCooling: true,
    costMaterial: "De 8 000 à 11 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 90 et 110 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Très faibles émissions de CO₂ : 15 g CO₂/kWhth en phase d'exploitation",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux importants dans les parties extérieures collectives pour le forage dans la nappe phréatique",
    emitterTypeRequired: "Efficace pour bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "La copropriété doit se trouver en zone GMI (orange ou vert). Zone rouge possible mais avec une procédure lourde et incertaine",
    indoorSpaceRequired: "10 à 20 m² nécessaires (machines, équipements hydrauliques, tableaux électriques…)",
    outdoorSpaceRequired: "Deux forages nécessaires à une distance déterminée par les études. La parcelle doit être accessible pour les machines de forage",
    otherConditions: [
      "Le potentiel de la nappe identifiée doit être fort ou très fort",
      "Entretien annuel minimum nécessaire pour garantir le bon fonctionnement",
      "La qualité du réseau de distribution de chaleur est essentielle pour le rendement global",
      "Retour sur investissement : 8 à 15 ans en moyenne",
      "Prévoir un autre système pour l'eau chaude sanitaire",
    ],
    fullDescription:
      "La pompe à chaleur eau-eau géothermique sur nappe utilise la chaleur d'une nappe phréatique pour chauffer l'eau pour les radiateurs. Très efficace et écologique, idéale si l'espace extérieur permet un forage et donc pas d'unité extérieure. Chauffage uniquement, prévoir un autre système pour l'ECS. Pertinent en rénovation globale ou bâtiment récent.",
    icon: GeothermieIcon,
    illustration: IllustrationGeothermieNappeHeatOnly,
    ficheEnr: FichePacEauGeothermieNappe,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Les Tilleuls",
      lieu: "Lassay-les-Châteaux",
      codeDepartement: "53",
      nbLogements: 85,
      nbm2: 4000,
      avantChauffage: "",
      avantECS: "",
      apresChauffage: "PAC géothermique pour le chauffage",
      apresECS: "",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["3 PAC géothermiques WPF 52", "2 ballons tampon SBP 1 500"],
      maitreOuvrage: "EHPAD Les Tilleuls",
      bureauEtude: "EICE",
      installateur: "SMEC",
      anneeLivraison: 2018,
      avantages: [
        "Réhabilitation complète du bâtiment avec agrandissement de la maison de retraite afin d’accueillir 85 personnes. Le chauffage est assuré par une cascade de 3 pompes à chaleur géothermiques, raccordées sur 26 forages.",
      ],
      images: ["/fiches-reference/23_01_01.jpg", "/fiches-reference/23_01_02.jpg"],
    },
  },
  {
    slug: "pac-eau-eau-sonde-chauffage-ecs",
    title: "Pompe à chaleur Eau / Eau géothermique sonde (chauffage + ECS)",
    type: "collectif",
    description: "Chauffe de l'eau en prélevant de la chaleur dans le sol via des sondes.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 8 000 à 11 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 110 et 160 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Très faibles émissions de CO₂ : 15 g CO₂/kWhth en phase d'exploitation",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux importants dans les parties extérieures collectives pour le forage dans le sol",
    emitterTypeRequired: "Efficace pour bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "La copropriété doit se trouver en zone GMI (orange ou vert). Zone rouge possible mais avec une procédure lourde et incertaine",
    indoorSpaceRequired: "10 à 20 m² nécessaires (machines, équipements hydrauliques, tableaux électriques…)",
    outdoorSpaceRequired: "La parcelle doit être accessible pour les machines de forage",
    otherConditions: [
      "Il est possible d'implanter des sondes géothermiques sur la parcelle permettant de produire une partie du chauffage et de l'eau chaude sanitaire",
      "Entretien annuel minimum nécessaire pour garantir le bon fonctionnement",
      "La qualité du réseau de distribution de chaleur est essentielle pour le rendement global",
      "Retour sur investissement : 8 à 15 ans en moyenne",
    ],
    fullDescription:
      "La pompe à chaleur eau glycolée-eau géothermique utilise la chaleur du sol pour chauffer l'eau (chauffage et ECS). Très efficace et écologique, idéale si l'espace extérieur permet un forage et donc pas d'unité extérieure. Possible uniquement en rénovation globale ou sur bâtiment récent. Nécessite un régime basse température pour être efficace.",
    icon: GeothermieIcon,
    illustration: IllustrationGeothermieSonde,
    ficheEnr: FichePacEauGeothermieSondes,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Rouget de l’Isle",
      lieu: "Pantin",
      codeDepartement: "93",
      nbLogements: 151,
      nbm2: 10055,
      anneeConstruction: 1966,
      avantChauffage: "Chaudière gaz et plancher chauffant",
      avantECS: "Chaudière gaz et plancher chauffant",
      apresChauffage: "PAC géothermique et chaudière gaz en appoint",
      apresECS: "PAC géothermique et chaudière gaz en appoint",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["RTWB 208, Trane", "2 chaudières gaz en appoint"],
      maitreOuvrage: "Immobilière 3F",
      bureauEtude: "Anteagroup, Sermet",
      installateur: "Cofely GDF Suez et Sanfor",
      anneeLivraison: 2011,
      avantages: [
        "Baisse des factures énergétiques de 59%",
        "Temps de retour sur investissement (avec subventions) : 6 ans",
        "PAC sur eau de nappe, puits de 68 m de profondeur et espacés de 280 m",
      ],
      images: ["/fiches-reference/13_01_01.jpg", "/fiches-reference/13_01_02.jpg"],
    },
  },
  {
    slug: "pac-eau-eau-sonde-chauffage",
    title: "Pompe à chaleur Eau / Eau géothermique sonde (chauffage seul)",
    type: "collectif",
    description: "Chauffe de l'eau en prélevant de la chaleur dans le sol via des sondes.",
    hasHeating: true,
    hasEcs: false,
    hasCooling: true,
    costMaterial: "De 8 000 à 11 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 110 et 160 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Très faibles émissions de CO₂ : 15 g CO₂/kWhth en phase d'exploitation",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux importants dans les parties extérieures collectives pour le forage dans le sol",
    emitterTypeRequired: "Efficace pour bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "La copropriété doit se trouver en zone GMI (orange ou vert). Zone rouge possible mais avec une procédure lourde et incertaine",
    indoorSpaceRequired: "10 à 20 m² nécessaires (machines, équipements hydrauliques, tableaux électriques…)",
    outdoorSpaceRequired: "La parcelle doit être accessible pour les machines de forage",
    otherConditions: [
      "Il est possible d'implanter des sondes géothermiques sur la parcelle permettant de produire une partie du chauffage",
      "Entretien annuel minimum nécessaire pour garantir le bon fonctionnement",
      "La qualité du réseau de distribution de chaleur est essentielle pour le rendement global",
      "Retour sur investissement : 8 à 15 ans en moyenne",
      "Prévoir un autre système pour l'eau chaude sanitaire",
    ],
    fullDescription:
      "La pompe à chaleur eau glycolée-eau géothermique utilise la chaleur du sol pour chauffer l'eau pour le chauffage. Très efficace et écologique, idéale si l'espace extérieur permet un forage et donc pas d'unité extérieure. Chauffage uniquement, prévoir un autre système pour l'ECS. Pertinent en rénovation globale ou bâtiment récent.",
    icon: GeothermieIcon,
    illustration: IllustrationGeothermieSondeHeatOnly,
    ficheEnr: FichePacEauGeothermieSondes,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Les Tilleuls",
      lieu: "Lassay-les-Châteaux",
      codeDepartement: "53",
      nbLogements: 85,
      nbm2: 4000,
      avantChauffage: "",
      avantECS: "",
      apresChauffage: "PAC géothermique pour le chauffage",
      apresECS: "",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["3 PAC géothermiques WPF 52", "2 ballons tampon SBP 1 500"],
      maitreOuvrage: "EHPAD Les Tilleuls",
      bureauEtude: "EICE",
      installateur: "SMEC",
      anneeLivraison: 2018,
      avantages: [
        "Réhabilitation complète du bâtiment avec agrandissement de la maison de retraite afin d’accueillir 85 personnes. Le chauffage est assuré par une cascade de 3 pompes à chaleur géothermiques, raccordées sur 26 forages.",
      ],
      images: ["/fiches-reference/23_01_01.jpg", "/fiches-reference/23_01_02.jpg"],
    },
  },
  {
    slug: "biomasse-chaudiere",
    title: "Biomasse (chaudière)",
    type: "collectif",
    description: "Chauffe de l'eau via une chaudière consommant de la biomasse.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "Variable selon la taille de la copropriété",
    costMaintenance: "Entretien annuel nécessaire",
    costMwh: "Granulés : 160–220 € HT/MWh, Plaquettes : 120–200 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Granulés : 32 g CO2/kWhPCI, Plaquettes : 27 g CO2/kWhPCI",
    noiseLevel: "Modérée en fonctionnement. Forte durant les livraisons (soufflage granulés / déchargement plaquettes)",
    installationImpact: "Faible : remplacement de la chaudière et ajout d'un silo de stockage",
    emitterTypeRequired: "Plancher chauffant à eau ou radiateurs à eau",
    distanceRequirement: "Accès camion < 20 m pour soufflage granulés ; silo plaquettes attenant au point de déchargement",
    indoorSpaceRequired: "Chaufferie 8–25 m² selon taille copro. Silo : 15–30 m² (granulés) et plus pour plaquettes",
    outdoorSpaceRequired: "Espace suffisant pour livraisons et stockage du combustible",
    otherConditions: [
      "Autorisation d'urbanisme possible. Intégration architecturale. En zone ABF, consulter les architectes des bâtiments de France",
      "Restrictions/interdictions en zones PPA (émissions de particules). Évacuation des fumées ≥ 9 m possible",
      "Contrat ≥ 3 ans recommandé (sécuriser prix/livraisons, éligibilité Fonds Chaleur). Privilégier origine locale et labels PEFC/FSC",
      "Vigilance sur stockage, surtout plaquettes. Taux d'humidité impacte rendement et émissions",
      "Compatible tous niveaux d'isolation. Possible mix bois/gaz (chaudière gaz en secours)",
    ],
    fullDescription:
      "Une chaudière biomasse utilise du bois (granulés ou plaquettes) pour produire chauffage et eau chaude sanitaire. Énergie renouvelable et locale. Deux combustibles : granulés (denses, standardisés) et plaquettes (bois déchiqueté, moins dense).",
    icon: BiomasseIcon,
    illustration: IllustrationBiomasse,
    ficheEnr: FicheBiomasse,
  },
  {
    slug: "pac-air-eau-collectif-chauffage-ecs",
    title: "Pompe à chaleur Air / Eau collective (chauffage + ECS)",
    type: "collectif",
    description: "Chauffe de l'eau en prélevant de la chaleur dans l'air via une unité extérieure.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 4 000 à 6 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 90 et 140 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (unité extérieure). Étude acoustique requise. Solutions d'atténuation possibles (murs antibruit, installation en parking sous-terrain)",
    installationImpact: "Travaux rapides dans des parties communes peu fréquentées",
    emitterTypeRequired: "Efficace avec eau basse température, adaptée aux bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "",
    indoorSpaceRequired: "6 à 12 m² intérieurs (module hydraulique, ballons, tableaux électriques…)",
    outdoorSpaceRequired: "8 à 16 m² extérieurs ventilés (cour, toiture, jardin, terrasse)",
    otherConditions: [
      "Autorisation d'urbanisme parfois requise, notamment en zone ABF. Intégration architecturale obligatoire",
      "Émergence sonore maximale : 5 dB(A) de jour (7h–22h), 3 dB(A) de nuit (22h–7h) selon le Code de la santé publique",
      "Alimentation électrique adaptée à la puissance. Devis à demander au gestionnaire de réseau",
      "Entretien annuel obligatoire pour garantir le bon fonctionnement",
      "Le réseau de distribution doit être vérifié (équilibrage, dimensionnement). Un réseau vétuste réduit fortement les performances",
    ],
    fullDescription:
      "La pompe à chaleur air/eau prélève la chaleur dans l'air extérieur, l'amplifie puis la transfère à un circuit d'eau pour le chauffage et l'eau chaude. Compatible avec les immeubles en chauffage collectif. Nécessite un espace extérieur et un local technique. Idéale en rénovation globale ou sur bâtiment récent.",
    icon: PACIcon,
    illustration: IllustrationPacAirEau,
    ficheEnr: FichePacAirEauCollective,
    example: {
      estNeuf: false,
      titrePrincipal: "Extension du foyer de l’Espérance",
      lieu: "Le Molay-Littry",
      codeDepartement: "14",
      nbLogements: 102,
      nbm2: 1600,
      avantChauffage: "",
      avantECS: "",
      anneeConstruction: 1995,
      apresChauffage: "PAC collective chauffage et ECS",
      apresECS: "PAC collective chauffage et ECS",
      isolation: "",
      detailMaterielsInstalles: ["4 PAC WPL 23", "3 PAC WPL 33", "5 ballons tampon SBP 700", "5 ballons ECS SBB 1 000 WP"],
      maitreOuvrage: "SCI Avenir",
      bureauEtude: "I2D Conseils",
      installateur: "Max Services 14",
      anneeLivraison: 2020,
      avantages: [
        "Le chantier portait sur la réhabilitation complète et l’extension du Foyer de l’Espérance en vue de pouvoir accueillir 102 résidents contre 86, initialement. Les PAC réalisent le chauffage et la production d’eau chaude sanitaire pour 5 bâtiments.",
      ],
      images: ["/fiches-reference/10_01_01.jpg", "/fiches-reference/10_01_02.jpg"],
    },
  },
  {
    slug: "pac-air-eau-collectif-chauffage",
    title: "Pompe à chaleur Air / Eau collective (chauffage seul)",
    type: "collectif",
    description: "Chauffe de l'eau en prélevant de la chaleur dans l'air via une unité extérieure.",
    hasHeating: true,
    hasEcs: false,
    hasCooling: true,
    costMaterial: "De 4 000 à 6 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 90 et 140 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (unité extérieure). Étude acoustique requise. Installation possible en parking pour limiter le bruit",
    installationImpact: "Travaux rapides dans des parties communes peu fréquentées",
    emitterTypeRequired: "Efficace avec eau basse température, adaptée aux bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "",
    indoorSpaceRequired: "6 à 12 m² intérieurs (module hydraulique, tableaux électriques…)",
    outdoorSpaceRequired: "8 à 16 m² extérieurs ventilés (cour, toiture, jardin, terrasse)",
    otherConditions: [
      "Autorisation d'urbanisme parfois requise, notamment en zone ABF. Intégration architecturale obligatoire",
      "Émergence sonore maximale : 5 dB(A) de jour (7h–22h), 3 dB(A) de nuit (22h–7h) selon le Code de la santé publique",
      "Alimentation électrique adaptée à la puissance. Devis à demander au gestionnaire de réseau",
      "Entretien annuel obligatoire pour garantir le bon fonctionnement",
      "Le réseau de distribution doit être vérifié (équilibrage, dimensionnement). Un réseau vétuste réduit fortement les performances",
      "Prévoir un autre système pour l'eau chaude sanitaire",
    ],
    fullDescription:
      "La pompe à chaleur air/eau capte la chaleur de l'air extérieur, la transfère à un circuit d'eau pour le chauffage uniquement. Un autre système est nécessaire pour l'eau chaude sanitaire (ECS). Solution performante et rentable en rénovation globale ou sur bâtiment récent.",
    icon: PACIcon,
    illustration: IllustrationPacAirEauHeatOnly,
    ficheEnr: FichePacAirEauCollective,
    example: {
      estNeuf: false,
      titrePrincipal: "Extension du foyer de l’Espérance",
      lieu: "Le Molay-Littry",
      codeDepartement: "14",
      nbLogements: 102,
      nbm2: 1600,
      avantChauffage: "",
      avantECS: "",
      anneeConstruction: 1995,
      apresChauffage: "PAC collective chauffage et ECS",
      apresECS: "PAC collective chauffage et ECS",
      isolation: "",
      detailMaterielsInstalles: ["4 PAC WPL 23", "3 PAC WPL 33", "5 ballons tampon SBP 700", "5 ballons ECS SBB 1 000 WP"],
      maitreOuvrage: "SCI Avenir",
      bureauEtude: "I2D Conseils",
      installateur: "Max Services 14",
      anneeLivraison: 2020,
      avantages: [
        "Le chantier portait sur la réhabilitation complète et l’extension du Foyer de l’Espérance en vue de pouvoir accueillir 102 résidents contre 86, initialement. Les PAC réalisent le chauffage et la production d’eau chaude sanitaire pour 5 bâtiments.",
      ],
      images: ["/fiches-reference/10_01_01.jpg", "/fiches-reference/10_01_02.jpg"],
    },
  },
  {
    slug: "hybride-pac-chaudiere-chauffage-ecs",
    title: "Hybridation Pompe à chaleur + chaudière (chauffage + ECS)",
    type: "collectif",
    description: "Combinaison d'une pompe à chaleur avec une chaudière pour assurer l'appoint.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 3 000 à 4 000 €",
    costMaintenance: "De 100 à 150 € / an",
    costMwh: "Dépend du taux de couverture entre pompe à chaleur et gaz",
    dpeGain: "Le gain dépend du taux de couverture des besoins couverts par la pompe à chaleur",
    co2Emissions: "Faibles émissions de CO₂ : entre 50 et 70 g CO₂/kWh",
    noiseLevel: "Niveau sonore de 45 à 65 dB (unité extérieure). Étude acoustique requise. Solutions d'atténuation possibles",
    installationImpact: "Travaux rapides dans des parties communes peu fréquentées",
    emitterTypeRequired: "Plancher chauffant à eau ou radiateur à eau",
    distanceRequirement: "",
    indoorSpaceRequired: "6 à 12 m² intérieurs (module hydraulique, ballons, tableaux électriques…)",
    outdoorSpaceRequired: "8 à 16 m² d'espace extérieur ventilé (cour, toiture, jardin, terrasse)",
    otherConditions: [
      "Autorisation d'urbanisme parfois requise. En zone ABF, consultation obligatoire des architectes des bâtiments de France",
      "Limite d'émergence sonore : 5 dB(A) jour (7h–22h), 3 dB(A) nuit (22h–7h), selon le Code de la santé publique",
      "Alimentation électrique adaptée à la puissance de l'équipement. Contacter le gestionnaire de réseau pour devis",
      "Entretien annuel obligatoire pour garantir le bon fonctionnement",
      "Vérification du réseau de distribution nécessaire (équilibrage, dimensionnement). Un réseau vétuste réduit les performances globales",
      "Double abonnement et double maintenance nécessaires (pompe à chaleur et chaudière)",
    ],
    fullDescription:
      "Cette solution combine une pompe à chaleur et une chaudière. La chaudière couvre une partie des besoins et fonctionne principalement quand il fait froid. Idéale si la solution pompe à chaleur seule n'est pas suffisante. Elle optimise le fonctionnement de la pompe à chaleur et réduit l'investissement initial, mais impose un double abonnement et une double maintenance. Il est recommandé de dimensionner la pompe à chaleur après rénovation pour correspondre aux futurs besoins du bâtiment.",
    icon: PACIcon,
    illustration: IllustrationHybride,
    ficheEnr: FicheHybridationPacChaudiere,
    example: {
      estNeuf: false,
      titrePrincipal: "Hôtel Les Coquelicots",
      lieu: "Saint-Pardoux-l’Ortigier",
      codeDepartement: "19",
      nbLogements: 25,
      nbm2: 900,
      anneeConstruction: 1977,
      avantChauffage: "Chaudière fioul",
      avantECS: "Chaudière fioul",
      apresChauffage: "PAC air-eau avec appoint gaz",
      apresECS: "PAC air-eau avec appoint gaz",
      isolation: "",
      detailMaterielsInstalles: [
        "AC ECS Hydrapac 11 kW",
        "ECS : Chaudière gaz Varfree 40 kW",
        "Ballon ECS Corydro 750 l",
        "PAC chauffage Aptaé 27 kW",
        "Chauffage : Chaudière gaz Varfree 70 kW",
      ],
      maitreOuvrage: "Hôtel Les Coquelicots",
      bureauEtude: "",
      installateur: "Faugeras Thermique Sanitaire",
      anneeLivraison: 2024,
      avantages: ["Avec Hydrapac, les économies sur la facture ECS sont de 25 à 30 % par rapport à la chaudière fioul existante."],
      images: ["/fiches-reference/15_01_01.jpg", "/fiches-reference/15_01_02.jpg"],
    },
  },
  {
    slug: "hybride-pac-chaudiere-chauffage",
    title: "Hybridation Pompe à chaleur + chaudière (chauffage seul)",
    type: "collectif",
    description: "Combinaison d'une pompe à chaleur avec une chaudière pour assurer l'appoint.",
    hasHeating: true,
    hasEcs: false,
    hasCooling: true,
    costMaterial: "De 3 000 à 4 000 €",
    costMaintenance: "De 100 à 150 € / an",
    costMwh: "Dépend du taux de couverture des besoins par le gaz",
    dpeGain: "Le gain dépend du taux de couverture des besoins couverts par la pompe à chaleur",
    co2Emissions: "Dépend du taux de couverture pompe à chaleur/chaudière. Faibles émissions de CO₂ : entre 50 et 70 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (unité extérieure). Étude acoustique requise. Installation possible en parking pour réduire le bruit",
    installationImpact: "Travaux rapides dans des parties communes peu fréquentées",
    emitterTypeRequired: "Plancher chauffant à eau ou radiateur à eau",
    distanceRequirement: "",
    indoorSpaceRequired: "6 à 12 m² en intérieur (module hydraulique, tableaux électriques…)",
    outdoorSpaceRequired: "8 à 16 m² d'espace extérieur ventilé",
    otherConditions: [
      "Autorisation d'urbanisme parfois requise. En zone ABF, consultation obligatoire des architectes des bâtiments de France",
      "Limite d'émergence sonore : 5 dB(A) jour (7h–22h), 3 dB(A) nuit (22h–7h), selon le Code de la santé publique",
      "Alimentation électrique adaptée à la puissance de l'équipement. Contacter le gestionnaire de réseau pour devis",
      "Entretien annuel obligatoire pour garantir le bon fonctionnement",
      "Vérification du réseau de distribution nécessaire (équilibrage, dimensionnement). Un réseau vétuste réduit les performances globales",
      "Double abonnement et double maintenance nécessaires (pompe à chaleur et chaudière)",
      "Prévoir un autre système pour l'eau chaude sanitaire",
    ],
    fullDescription:
      "Cette solution combine une pompe à chaleur et une chaudière. La chaudière couvre une partie des besoins et fonctionne principalement lorsqu'il fait froid. Idéale si la pompe à chaleur seule n'est pas envisageable. Optimise le fonctionnement de la pompe à chaleur et réduit l'investissement initial, mais impose un double abonnement et une double maintenance. Il est conseillé de dimensionner la pompe à chaleur après rénovation pour correspondre aux futurs besoins du bâtiment.",
    icon: PACIcon,
    illustration: IllustrationHybrideHeatOnly,
    ficheEnr: FicheHybridationPacChaudiere,
    example: {
      estNeuf: false,
      titrePrincipal: "Ecole Estienne d’Orves",
      lieu: "Verrières-le-Buisson",
      codeDepartement: "91",
      avantChauffage: "Chaudière gaz",
      avantECS: "Chaudière gaz",
      apresChauffage: "PAC air-eau pour le chauffage avec appoint gaz",
      apresECS: "",
      isolation: "",
      detailMaterielsInstalles: ["2 Effipac 50 kW", "Chaudière gaz"],
      maitreOuvrage: "Ville de Verrières-le-Buisson",
      bureauEtude: "Sage énergies",
      installateur: "CPE maintenance",
      anneeLivraison: 2023,
      avantages: [
        "Il a été installé 2 EFFIPAC chauffage de 50 KW dimensionnés pour assurer 30 % de la puissance par -7 °C extérieur soit une couverture annuelle d'environ 75 % et l'appoint est réalisé par la chaufferie gaz existante.",
      ],
      images: ["/fiches-reference/25_01_01.jpg", "/fiches-reference/25_01_02.jpg"],
    },
  },
  {
    slug: "solaire-thermique",
    title: "Solaire Thermique",
    type: "individuel",
    description: "Produit l'eau chaude sanitaire grâce à des capteurs installés généralement sur la toiture.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "1200 à 1300 € / m² de capteur",
    costMaintenance: "~ 10 € / m² de capteur / an",
    costMwh: "Entre 140 et 200 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Aucun CO₂ en fonctionnement. En incluant la fabrication : 8 g CO₂/kWh pour le capteur seul, 60 g CO₂/kWh avec stockage",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux modérés mais complexes si espace technique ou structure contraignants",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Un local pour le ballon de stockage",
    outdoorSpaceRequired: "Environ 2 m² de toiture par logement pour les capteurs",
    otherConditions: [
      "Orientation sud/sud-ouest, inclinaison 30–60°, sans ombrage",
      "Attention au surdimensionnement : prévoir système autovidangeable ou besoins continus en été",
      "Entretien annuel minimum nécessaire pour garantir la performance",
      "Système d'appoint nécessaire pour relais en cas de faible ensoleillement",
      "Prévoir un ballon d'eau chaude d'environ 50 L/m² de panneau",
      "Autorisation d'urbanisme souvent requise. En zone ABF, consultation obligatoire des architectes des bâtiments de France",
    ],
    fullDescription:
      "Les capteurs solaires captent le rayonnement solaire et réchauffent un fluide caloporteur transférant la chaleur à un ballon d'eau chaude via un échangeur. Solution fiable et mature, idéale pour la production d'eau chaude sanitaire, surtout en toiture terrasse.",
    icon: SolaireThermiqueIcon,
    illustration: IllustrationSolaireThermiqueWaterOnly,
    ficheEnr: FicheSolaireThermique,
  },
  {
    slug: "pac-capteurs-atmospheriques-ecs",
    title: "Pompe à chaleur Eau / Eau sur capteurs atmosphériques",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant de la chaleur dans l'eau réchauffée par des capteurs.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "De 3 000 à 4 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 140 et 200 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Très faibles émissions de CO₂ : 15 g CO₂/kWhth",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux modérés, parfois complexes selon la configuration du toit ou du local technique",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Local pour ballon de stockage",
    outdoorSpaceRequired: "Environ 1 m² de toiture par logement pour les capteurs",
    otherConditions: [
      "Autorisation d'urbanisme souvent requise. En zone ABF, consultation obligatoire des architectes des bâtiments de France",
      "Entretien annuel minimum pour garantir le bon fonctionnement",
      "Un autre système est nécessaire pour le chauffage",
    ],
    fullDescription:
      "La pompe à chaleur sur capteurs solaires atmosphériques utilise la chaleur du soleil pour chauffer l'eau sanitaire. Les capteurs installés en toiture réchauffent le fluide utilisé par la pompe à chaleur. Un autre système est nécessaire pour le chauffage.",
    icon: SolaireThermiqueIcon,
    illustration: IllustrationCapteurAtmospheriqueWaterOnly,
    ficheEnr: FichePacCapteursAtmospheriques,
    example: {
      estNeuf: false,
      titrePrincipal: "La Marseillaise",
      lieu: "Nantes",
      codeDepartement: "44",
      nbLogements: 0,
      nbm2: 858,
      anneeConstruction: 1927,
      avantChauffage: "Gaz collectif",
      avantECS: "Gaz collectif",
      apresChauffage: "ECS par PAC sur capteur solaire atmosphérique",
      apresECS: "ECS par PAC sur capteur solaire atmosphérique",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["PAC", "2 ballons 1000 l", "66 m² capteurs"],
      maitreOuvrage: "GALEO",
      bureauEtude: "Pouget Consultants",
      installateur: "ABG Climatique",
      anneeLivraison: 2018,
      avantages: ["Les capteurs solaires hybrides produisent à la fois de l’eau chaude sanitaire et de l’électricité photovoltaïque. Le projet est labélisé SMILE."],
      images: ["/fiches-reference/04_01_01.jpg", "/fiches-reference/04_01_02.jpg"],
    },
  },
  {
    slug: "pac-eaux-grises-ecs",
    title: "Pompe à chaleur sur eaux grises / eau",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant de la chaleur dans les eaux grises.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "De 4 000 à 5 000 € (ajouter coût des canalisations pour le recueil des eaux usées)",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 80 et 120 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Très faibles émissions de CO₂ : 15 g CO₂/kWhth en phase d'exploitation",
    noiseLevel: "Aucune nuisance sonore",
    installationImpact: "Travaux importants : installation du circuit de collecte des eaux grises",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Environ 20 à 30 m² de local technique (machines, équipements hydrauliques, tableaux électriques…)",
    outdoorSpaceRequired: "",
    otherConditions: ["Entretien annuel minimum pour garantir le bon fonctionnement", "Nécessite un double circuit pour la récupération et la réutilisation de la chaleur"],
    fullDescription:
      "La pompe à chaleur eaux grises-eau récupère la chaleur des eaux usées (douches, vaisselle) pour chauffer l'eau sanitaire. Nécessite un double circuit pour la récupération et la réutilisation de la chaleur. Solution adaptée pour l'eau chaude sanitaire (ECS) collective avec un local technique (machine + ballon de stockage).",
    icon: PACIcon,
    illustration: IllustrationPacEauxGrisesWaterOnly,
    ficheEnr: FichePacEauxGrises,
    example: {
      estNeuf: true,
      titrePrincipal: "Eole Evangile",
      lieu: "Paris",
      codeDepartement: "75",
      nbLogements: 167,
      nbm2: 8000,
      anneeConstruction: 2021,
      apresChauffage: "Chauffage électrique",
      apresECS: "PAC sur eaux grise",
      isolation: "Bâtiment neuf RT2012",
      detailMaterielsInstalles: ["PAC facteur 7"],
      maitreOuvrage: "Linkcity",
      bureauEtude: "Amoes",
      installateur: "Bouygues Construction",
      avantages: ["COP effectif mesuré de l’ordre de 5 pour la production ECS", "COP effectif mesuré de l’ordre de 4 pour la production ECS et le Bouclage"],
      images: ["/fiches-reference/03_01_01.jpg", "/fiches-reference/03_01_02.jpg"],
    },
  },
  {
    slug: "pac-air-eau-ecs",
    title: "Pompe à chaleur air/eau dédiée à l'ECS",
    type: "individuel",
    description: "Chauffe de l'eau pour produire l'eau chaude sanitaire (ECS) en prélevant la chaleur dans l'air via une unité extérieure.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "De 2 000 à 3 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 80 et 130 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (extérieur) / 50 à 65 dB (intérieur). Étude acoustique requise",
    installationImpact: "Travaux rapides dans les parties communes peu fréquentées",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "6 à 12 m² intérieurs (module hydraulique, ballons, tableaux électriques…)",
    outdoorSpaceRequired: "8 à 16 m² extérieurs ventilés (cour, toiture, jardin)",
    otherConditions: [
      "Autorisation d'urbanisme parfois requise. En zone ABF, consultation obligatoire des architectes des bâtiments de France",
      "Émergence sonore max : 5 dB(A) jour (7h–22h), 3 dB(A) nuit (22h–7h) selon le Code de la santé publique",
      "Alimentation adaptée à la puissance. Devis à demander au gestionnaire de réseau",
      "Entretien annuel obligatoire pour garantir le bon fonctionnement",
      "Un autre système est requis pour le chauffage",
    ],
    fullDescription:
      "Cette solution ne chauffe que l'eau sanitaire. Elle nécessite un local technique (machine + ballon de stockage) et un espace extérieur pour l'unité extérieure. Un autre système est requis pour le chauffage.",
    icon: PACIcon,
    illustration: IllustrationPacAirEauWaterOnly,
    ficheEnr: FichePacAirEauCollectiveEcs,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Corcieux",
      lieu: "Corcieux",
      codeDepartement: "88",
      nbLogements: 12,
      nbm2: 0,
      anneeConstruction: 1960,
      avantChauffage: "Chaudière gaz",
      avantECS: "Chaudière gaz",
      apresChauffage: "Chaudière bois pour le chauffage",
      apresECS: "ECS par PAC",
      isolation: "",
      detailMaterielsInstalles: ["1 HRC70 35 kW"],
      maitreOuvrage: "Le Toit Vosgien",
      bureauEtude: "Terranergie",
      installateur: "Eury",
      anneeLivraison: 2019,
      avantages: ["Bâtiment passif"],
      images: ["/fiches-reference/01_02_01.jpg", "/fiches-reference/01_02_02.jpg"],
    },
  },
  {
    slug: "pac-air-eau-individuel-unite-exterieure",
    title: "Pompe à chaleur air/eau avec unité extérieure",
    type: "individuel",
    description: "Chauffe de l'eau pour le chauffage et l'ECS en prélevant la chaleur dans l'air via une unité extérieure.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 7 000 à 10 000 €",
    costMaintenance: "~ 250 € / an",
    costMwh: "Entre 120 et 160 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (extérieur). Solutions d'atténuation possibles (caissons, isolation)",
    installationImpact: "Travaux de remplacement du système dans l'appartement",
    emitterTypeRequired: "Efficace avec eau basse température, adaptée aux bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "",
    indoorSpaceRequired: "Espace intérieur (taille d'un frigo) pour la pompe à chaleur et le ballon d'eau chaude sanitaire",
    outdoorSpaceRequired: "Espace extérieur (balcon possible) pour l'unité",
    otherConditions: [
      "Émergence sonore max : 5 dB(A) jour (7h–22h), 3 dB(A) nuit (22h–7h)",
      "Abonnement plus puissant requis. Vérifier avec le gestionnaire si plusieurs pompes à chaleur sont installées dans l'immeuble",
      "Entretien annuel obligatoire",
      "Désembouage du réseau de radiateurs recommandé",
    ],
    fullDescription:
      "La pompe à chaleur air/eau chauffe l'eau pour les radiateurs et l'eau chaude en utilisant l'air extérieur. Système individuel nécessitant une unité intérieure et une unité extérieure.",
    icon: PACIcon,
    illustration: IllustrationPacAirEauAvecUE,
    ficheEnr: FichePacAirEauAvecUe,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Urimenil",
      lieu: "Urimenil",
      codeDepartement: "88",
      nbLogements: 20,
      nbm2: 1500,
      anneeConstruction: 1975,
      avantChauffage: "Chaudière individuelle fioul",
      avantECS: "Chauffe-eau électrique individuel",
      apresChauffage: "PAC individuelle",
      apresECS: "PAC individuelle",
      isolation: "Isolation par l’extérieur des murs",
      detailMaterielsInstalles: ["Arianext Compact"],
      maitreOuvrage: "Offre Public de l'Habitat",
      bureauEtude: "Fluid'Concept",
      installateur: "CPIS",
      anneeLivraison: 2021,
      avantages: [
        "Remplacement d’une chaudière à fioul et de chauffe-eau électrique par une PAC pour le chauffage et l’ECS faisant passer la classe énergétique de la section E-G à B-C.",
      ],
      images: ["/fiches-reference/50_01_01.jpg", "/fiches-reference/50_01_02.jpg"],
    },
  },
  {
    slug: "pac-air-eau-individuel-sans-unite-exterieure",
    title: "Pompe à chaleur air/eau sans unité extérieure",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant la chaleur dans l'air via un réseau de gaines connecté à l'extérieur.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 9 000 à 11 000 €",
    costMaintenance: "~ 250 € / an",
    costMwh: "Entre 120 et 160 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "Faible nuisance sonore intérieure",
    installationImpact: "Travaux de remplacement du système dans l'appartement",
    emitterTypeRequired: "Efficace avec eau basse température, adaptée aux bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "",
    indoorSpaceRequired: "Unité intérieure (taille d'un frigo)",
    outdoorSpaceRequired: "Gaine d'aspiration et sortie sur façade",
    otherConditions: [
      "Abonnement plus puissant requis. Vérifier avec le gestionnaire si plusieurs pompes à chaleur sont installées",
      "Entretien annuel obligatoire",
      "Désembouage du réseau de radiateurs recommandé",
    ],
    fullDescription:
      "La pompe à chaleur air/eau sans unité extérieure utilise un réseau de gaines pour capter l'air extérieur et chauffer l'eau et l'air intérieur. Solution individuelle assurant chauffage et eau chaude sanitaire.",
    icon: PACIcon,
    illustration: IllustrationPacAirEauSansUE,
    ficheEnr: FichePacAirEauSansUe,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence",
      lieu: "Rennes",
      codeDepartement: "35",
      nbLogements: 20,
      avantChauffage: "Convecteurs électriques",
      avantECS: "Chauffe-eau électrique individuel",
      apresChauffage: "PAC air-eau sans unité extérieure",
      apresECS: "PAC air-eau sans unité extérieure",
      isolation: "",
      detailMaterielsInstalles: ["PAC OPTIM’DUO"],
      maitreOuvrage: "Espacil Habitat",
      bureauEtude: "",
      installateur: "",
      anneeLivraison: 2016,
      avantages: ["Installation dans les combles", "Facture de chauffage et ECS divisée par 6", "Passage en étiquette DPE B"],
      images: ["/fiches-reference/51_01_01.jpg", "/fiches-reference/51_01_02.jpg"],
    },
  },
  {
    slug: "pac-air-extrait-eau",
    title: "Pompe à chaleur air extrait/eau",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant la chaleur dans l'air extrait du système de ventilation.",
    hasHeating: true,
    hasEcs: true,
    hasCooling: true,
    costMaterial: "De 9 000 à 12 000 €",
    costMaintenance: "~ 250 € / an",
    costMwh: "Entre 120 et 160 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "Faible nuisance sonore intérieure",
    installationImpact: "Travaux de remplacement du système dans l'appartement",
    emitterTypeRequired: "Efficace avec eau basse température, adaptée aux bâtiments bien isolés ou équipés de planchers chauffants",
    distanceRequirement: "",
    indoorSpaceRequired: "Espace intérieur pour la pompe à chaleur produisant chauffage et eau chaude sanitaire, taille environ celle d'un réfrigérateur",
    outdoorSpaceRequired: "",
    otherConditions: [
      "Abonnement de plus grande puissance requis. Vérifier avec le gestionnaire du réseau si plusieurs installations dans l'immeuble",
      "Entretien annuel obligatoire pour garantir le bon fonctionnement",
      "Désembouage du réseau de radiateurs recommandé",
    ],
    fullDescription:
      "La pompe à chaleur sur air extrait s'intègre au système de ventilation pour produire le chauffage et l'eau chaude sanitaire. Bonne solution lorsque l'espace extérieur est limité. Solution individuelle assurant chauffage et eau chaude sanitaire.",
    icon: PACIcon,
    illustration: IllustrationPacAirExtraitEau,
    ficheEnr: FichePacAirExtraitEau,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Flers",
      lieu: "Flers",
      codeDepartement: "61",
      nbLogements: 112,
      anneeConstruction: 1963,
      avantChauffage: "Chaudière à gaz centrale",
      avantECS: "Chauffe-bains individuels à gaz",
      apresChauffage: "PAC sur air extrait de VMC",
      apresECS: "PAC sur air extrait de VMC",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["112 PAC F730"],
      maitreOuvrage: "Logissia / M2OB",
      bureauEtude: "",
      installateur: "SCETEC",
      anneeLivraison: 2024,
      avantages: ["Sans unité extérieure"],
      images: ["/fiches-reference/53_01_01.jpg", "/fiches-reference/53_01_02.jpg"],
    },
  },
  {
    slug: "pac-air-air",
    title: "Pompe à chaleur air/air",
    type: "individuel",
    description: "Chauffe ou refroidit l'air en prélevant la chaleur dans l'air via une unité extérieure.",
    hasHeating: true,
    hasEcs: false,
    hasCooling: true,
    costMaterial: "De 3 000 à 5 000 €",
    costMaintenance: "~ 100 € / an",
    costMwh: "Entre 110 et 160 € HT/MWh",
    dpeGain: "Gain de 1 à 2 classes",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (extérieur). Des solutions existent pour réduire le bruit",
    installationImpact: "Travaux de remplacement du système dans l'appartement",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Splits muraux intérieurs (mono ou multi-split)",
    outdoorSpaceRequired: "Unité extérieure (balcon possible)",
    otherConditions: [
      "Abonnement électrique plus puissant requis. Vérifier si plusieurs pompes à chaleur sont installées",
      "Entretien annuel obligatoire pour garantir la performance",
      "En mode climatisation, la chaleur rejetée à l'extérieur contribue aux îlots de chaleur urbains",
      "Ne produit pas d'eau chaude sanitaire",
    ],
    fullDescription:
      "La pompe à chaleur air/air utilise l'air extérieur comme source d'énergie pour chauffer ou refroidir l'air intérieur. Remplace les radiateurs électriques et souffle de l'air chaud. Ne produit pas d'eau chaude sanitaire.",
    icon: PACIcon,
    illustration: IllustrationPacAirAirHeatOnly,
    ficheEnr: FichePacAirAir,
    example: {
      estNeuf: false,
      titrePrincipal: "Particulier",
      lieu: "",
      nbLogements: 0,
      nbm2: 0,
      anneeConstruction: 0,
      avantChauffage: "",
      avantECS: "",
      apresChauffage: "PAC air-air monosplit",
      apresECS: "PAC air-air monosplit",
      isolation: "",
      detailMaterielsInstalles: [],
      maitreOuvrage: "",
      bureauEtude: "",
      installateur: "E-Climat",
      anneeLivraison: 2024,
      avantages: ["Cache extérieur DECOCLIM en aluminium"],
      images: ["/fiches-reference/40_01_01.jpg", "/fiches-reference/40_01_02.jpg", "/fiches-reference/40_01_03.jpg"],
    },
  },
  {
    slug: "chauffe-eau-thermodynamique-exterieur",
    title: "Chauffe-eau thermodynamique avec unité extérieure",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant la chaleur dans l'air via une unité extérieure.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "De 3 000 à 5 000 €",
    costMaintenance: "~ 50 € / an",
    costMwh: "Entre 210 et 250 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "45 à 65 dB (extérieur). Des traitements acoustiques existent",
    installationImpact: "Travaux de remplacement du système dans l'appartement",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Chauffe-eau thermodynamique intérieur (taille d'un ballon d'eau chaude)",
    outdoorSpaceRequired: "Unité extérieure (balcon possible)",
    otherConditions: ["Entretien annuel obligatoire pour garantir le bon fonctionnement"],
    fullDescription: "Le chauffe-eau thermodynamique chauffe l'eau sanitaire en récupérant l'énergie de l'air extérieur via une unité installée à l'extérieur.",
    icon: PACIcon,
    illustration: IllustrationCetAvecUEWaterOnly,
    ficheEnr: FicheChauffeEauThermodynamiqueAvecUe,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Rue de la Croix",
      lieu: "Nanterre",
      codeDepartement: "92",
      nbLogements: 74,
      avantChauffage: "",
      avantECS: "Chauffe-eau électrique",
      apresChauffage: "",
      apresECS: "CET sur air extérieur",
      isolation: "",
      detailMaterielsInstalles: ["Calypso"],
      maitreOuvrage: "Erigere",
      bureauEtude: "",
      installateur: "Bedier",
      anneeLivraison: 2021,
      avantages: [],
      images: ["/fiches-reference/31_01_01.jpg", "/fiches-reference/31_01_02.jpg"],
    },
  },
  {
    slug: "chauffe-eau-thermodynamique-interieur",
    title: "Chauffe-eau thermodynamique sans unité extérieure",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant la chaleur dans l'air via une gaine.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "De 3 000 à 5 000 €",
    costMaintenance: "~ 50 € / an",
    costMwh: "Entre 210 et 250 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "Faible nuisance sonore intérieure",
    installationImpact: "Travaux simples de remplacement du système existant",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Espace intérieur nécessaire pour le chauffe-eau thermodynamique (taille d'un gros ballon d'eau chaude)",
    outdoorSpaceRequired: "Gaines d'entrée et de sortie d'air",
    otherConditions: ["Entretien annuel obligatoire pour assurer la performance et la durabilité"],
    fullDescription:
      "Le chauffe-eau thermodynamique chauffe l'eau sanitaire en puisant l'énergie dans l'air extérieur à travers une gaine. Solution compacte adaptée aux logements sans possibilité d'installation extérieure.",
    icon: PACIcon,
    illustration: IllustrationCetSansUEWaterOnly,
    ficheEnr: FicheChauffeEauThermodynamiqueSansUe,
    example: {
      estNeuf: true,
      titrePrincipal: "Résidence Rue du Bourgneuf",
      lieu: "Hennebont",
      codeDepartement: "56",
      nbLogements: 37,
      anneeConstruction: 2024,
      apresChauffage: "Chauffage électrique",
      apresECS: "CET sur air extérieur, installé dans les logements avec bouche en façade",
      isolation: "Bâtiment neuf RE2020",
      detailMaterielsInstalles: ["Edel 100 (T2)", "Edel 150 (T3)", "Edel 200 (T4)", "Edel 270 (T5)"],
      maitreOuvrage: "Nexity",
      bureauEtude: "Pouget Consultants",
      installateur: "Climatech Ouest",
      avantages: ["Le projet atteint le seuil 2025 de la RE2020."],
      images: ["/fiches-reference/32_01_01.jpg", "/fiches-reference/32_01_02.jpg"],
    },
  },
  {
    slug: "chauffe-eau-thermodynamique-air-extrait",
    title: "Chauffe-eau thermodynamique air extrait",
    type: "individuel",
    description: "Chauffe de l'eau en prélevant la chaleur dans l'air du système de ventilation.",
    hasHeating: false,
    hasEcs: true,
    hasCooling: false,
    costMaterial: "De 3 000 à 5 000 €",
    costMaintenance: "~ 50 € / an",
    costMwh: "Entre 210 et 250 € HT/MWh",
    dpeGain: "Gain de 0 à 1 classe",
    co2Emissions: "Faibles émissions de CO₂ : 50 g CO₂/kWh",
    noiseLevel: "Faible nuisance sonore intérieure",
    installationImpact: "Travaux simples de remplacement du système existant",
    emitterTypeRequired: "",
    distanceRequirement: "",
    indoorSpaceRequired: "Espace intérieur nécessaire pour le chauffe-eau thermodynamique (taille d'un gros ballon d'eau chaude)",
    outdoorSpaceRequired: "",
    otherConditions: ["Entretien annuel obligatoire pour garantir le bon fonctionnement"],
    fullDescription:
      "Le chauffe-eau thermodynamique sur air extrait s'intègre au système de ventilation pour produire l'eau chaude sanitaire (ECS). Idéal lorsque l'espace extérieur est limité.",
    icon: PACIcon,
    illustration: IllustrationCetAirExtraitWaterOnly,
    ficheEnr: FicheChauffeEauThermodynamiqueAirExtrait,
    example: {
      estNeuf: false,
      titrePrincipal: "Résidence Les Primevères",
      lieu: "Taverny",
      codeDepartement: "95",
      nbLogements: 112,
      nbm2: 8129,
      anneeConstruction: 1982,
      avantChauffage: "",
      avantECS: "Chauffe-eau électrique",
      apresChauffage: "",
      apresECS: "CET sur air extrait de VMC pour l’ECS",
      isolation: "Rénovation globale (fenêtres, murs, toiture, plancher)",
      detailMaterielsInstalles: ["Aquacosy SV"],
      maitreOuvrage: "CDC Habitat",
      bureauEtude: "SOGETI INGENIERIE Bâtiment",
      installateur: "GCC",
      anneeLivraison: 2024,
      avantages: [
        "Les 112 logements sont répartis sur 5 bâtiments (R+3 à R+7) équipés de 4 ascenseurs.",
        "Certification NF Habitat HQE et HPE Rénovation. Réhabilitation en site occupé et en présence d’amiante.",
      ],
      images: ["/fiches-reference/30_01_01.jpg", "/fiches-reference/30_01_02.jpg"],
    },
  },
];
